name: ${NAME}
arch: ${ARCH}
version: ${VERSION}
priority: optional
maintainer: Nick Ng <ngyewch@gmail.com>
description: |
  The Cloud Native Application Proxy
homepage: https://github.com/traefik/traefik
license: MIT

contents:
  - src: ${ARCHIVE_DIR}/traefik
    dst: /usr/bin/traefik
    expand: true
  - src: contents
    dst: /
    type: tree
scripts:
  preinstall: scripts/preinstall.sh
  postinstall: scripts/postinstall.sh
  preremove: scripts/preremove.sh
  postremove: scripts/postremove.sh
